version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - plausible_internal

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    networks:
      - plausible_internal
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_events_db
      - mail
    ports:
      - 4000:8000
    networks:
      - plausible_internal
    environment:
      BASE_URL: https://plausible.hjemmesidekongen.dk
      SECRET_KEY_BASE: 599888d84f45f0f9cc28ef4687bf2495611f6c4547eb2db3721801a0d1c1c0ed

volumes:
  event-data:
    driver: local

networks:
  plausible_internal:
