name: Deploy to VPS via SSH with Docker Compose

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy_via_ssh:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy compose file via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          port: 22
          source: "./docker-compose.yml"
          target: "~/sites/${{ github.event.repository.name }}"

      - name: Remote docker-compose up via ssh
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          port: 22
          script: |
            docker compose -f ~/sites/${{ github.event.repository.name }}/docker-compose.yml pull
            docker compose -f ~/sites/${{ github.event.repository.name }}/docker-compose.yml up -d
